export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const SAVING_QUESTION_ANSWER = 'SAVING_QUESTION_ANSWER';
export const SAVED_QUESTION_ANSWER = 'SAVED_QUESTION_ANSWER';

export const AUTH_USER = 'AUTH_USER';
export const LOG_OUT = 'LOG_OUT';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const UPDATE_QUESTION_ON_QUESTION_SAVE = 'UPDATE_QUESTION_ON_QUESTION_SAVE';
export const UPDATE_QUESTION_ON_CREATE = 'UPDATE_QUESTION_ON_CREATE';

export const GET_USERS = 'GET_USERS';
export const UPDATE_USER_ON_QUESTION_SAVE = 'UPDATE_USER_ON_QUESTION_SAVE';
export const UPDATE_USER_ON_CREATE = 'UPDATE_USER_ON_CREATE';
